# Generated by Django 2.0.8 on 2018-08-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_datee',
            new_name='published_date',
        ),
    ]
